spring:
  datasource:
    url: 'jdbc:mysql://karrotdb.ctccq2e04brz.ap-northeast-2.rds.amazonaws.com:3306/karrotdb'
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: somepassword
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        show_sql: false
  profiles:
    active: dev

cache:
  expire-after-write: 1m
  maximum-size: 100