spring:
  datasource:
    url: 'jdbc:mysql://52.78.132.59:3306/mysql'
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: dev
    password: somepassword
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
    properties:
      hibernate:
        show_sql: false
  profiles:
    active: dev

cache:
  expire-after-write: 1m
  maximum-size: 100