spring:
  datasource:
    url: 'jdbc:mysql://52.78.132.59:3306/mysql'
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: dev
    password: somepassword
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
    properties:
      hibernate:
        show_sql: false
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: '${GOOGLE_CLI_ID}'
            clientSecret: '${GOOGLE_CLI_SECRET}'
            redirect-uri: "https://toykarrot.shop/{action}/oauth2/code/{registrationId}"
            scope:
              - email
              - profile
          naver:
            clientId: '${NAVER_CLI_ID}'
            clientSecret: '${NAVER_CLI_SECRET}'
            clientAuthenticationMethod: client_secret_post
            authorizationGrantType: authorization_code
            redirectUri: "https://toykarrot.shop/{action}/oauth2/code/{registrationId}"
            scope:
              - nickname
              - email
              - profile_image
            clientName: Naver
          kakao:
            clientId: '${KAKAO_CLI_ID}'
            clientSecret: '${KAKAO_CLI_SECRET}'
            clientAuthenticationMethod: client_secret_post
            authorizationGrantType: authorization_code
            redirectUri: "https://toykarrot.shop/{action}/oauth2/code/{registrationId}"
            scope:
              - profile_nickname
              - profile_image
              - account_email
            clientName: Kakao
        provider:
          naver:
            authorizationUri: https://nid.naver.com/oauth2.0/authorize
            tokenUri: https://nid.naver.com/oauth2.0/token
            userInfoUri: https://openapi.naver.com/v1/nid/me
            user-info-authentication-method: header
            userNameAttribute: response
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: header
            userNameAttribute: id
  profiles:
    active: dev
logging:
  level:
    org.springframework.security: DEBUG