package com.toyProject7.karrot.manner.controller

enum class MannerType {
    KINDNESS,
    PUNCTUALITY,
    QUICK_RESPONSE,
    DELIVERY,
    ACCURATE_DESCRIPTION,
    AFFORDABLE_PRICE,
    DETAILED_DESCRIPTION,
    SHARING,
    NEG_KINDNESS,
    NEG_PUNCTUALITY,
    NEG_QUICK_RESPONSE,
    NEG_DELIVERY,
    NEG_ACCURATE_DESCRIPTION,
    NEG_AFFORDABLE_PRICE,
    NEG_DETAILED_DESCRIPTION,
    NEG_SHARING,
}
