# github repository actions 페이지에 나타날 이름
name: CI/CD Pipeline

# event trigger
# main이나 develop 브랜치에 push가 되었을 때 실행
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:

      # JDK setting - github actions에서 사용할 JDK 설정 (프로젝트나 AWS의 java 버전과 달라도 무방)
      - uses: actions/checkout@v4
      - name: Set up JDK 17 and Eclipse Temurin
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 린트 체크 실행
      - name: Lint Check
        run: ./gradlew ktlintCheck

      # gradle build
      - name: Build with Gradle
        run: ./gradlew build -x test
