name: Load Secrets From Github

on:
  push:
    branches:
      - main
      - "feat/*"
  pull_request:
    branches:
      - "main"
      - "feat/*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Gradle
        env:
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLI_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLI_SECRET }}
          NAVER_CLIENT_ID: ${{ secrets.NAVER_CLI_ID }}
          NAVER_CLIENT_SECRET: ${{ secrets.NAVER_CLI_SECRET }}
          KAKAO_CLIENT_ID: ${{ secrets.KAKAO_CLI_ID }}
          KAKAO_CLIENT_SECRET: ${{ secrets.KAKAO_CLI_SECRET }}
        run: ./gradlew build